%% Pick out chirps in model generation

clear

% find all relevant files generated by RunParameterSpace.m
dirName = 'BirdSongSims/';
birdSongFiles = dir([dirName '*.mat']);

Fs = 22050;  % sampling rate

numChirps = 0; % initialize variales 
chirpDurations = 0;

for ii = 1:size(birdSongFiles, 1) % for each file 
    load([dirName birdSongFiles(ii).name]); % load the file 
    s1_sm = conv(abs(s1), ones(100,1), 'same')/100; % smooth the rectified sound trace 
    myEnv = s1_sm > power(10,-4); % find regions where the sound trace goes above a certain value 
    myEnv_diff = myEnv(2:end) - myEnv(1:end-1); % find where envelopes defining syllables start and end 
    myEnds = find(myEnv_diff == -1);
    myStarts = find(myEnv_diff == 1);
    if isempty(myEnds) % fix any special cases that may arise in defining envelopes 
        myEnds = myStarts(1) + 6000;
    end
    if myEnds(1) < myStarts(1) 
        myEnds = myEnds(2:end);
    end
    if isempty(myEnds) 
        myEnds = myStarts(1) + 6000;
    end
    if myEnds(end) < myStarts(end) 
        myEnds = [myEnds; size(s1,1)];
    end
    for jj = 1:size(myStarts, 1) % go through each envelope and grab the syllables or "chirps"
        if (myEnds(jj) - myStarts(jj)) >= 1000 && (myEnds(jj) - myStarts(jj)) <= 6000
            numChirps = numChirps + 1;
            thisChirp = zeros(6000,1);
            chirpLength = myEnds(jj) - myStarts(jj) + 1;
            thisChirp(1:chirpLength) = s1(myStarts(jj):myEnds(jj)); 
            myChirps{numChirps} = thisChirp;  
            chirpDurations(numChirps) = chirpLength;
        end
    end       
end

% save the data in an appropriate folder 
save('Data/AllChirps.mat', 'myChirps', 'chirpDurations')
